### ISSUE TITLE
running error?

### ISSUE THREAD

**Issue by kyw220** [alexzheng42/sDMD#1]
Dear sDMD, 

I am new to sDMD and I am trying to run a single protein system as a test run from generation of the .gro file to actual run. However, I need your helps due to the error.

I prepared pdb file and used GROMACS pdb2gmx to convert it to .gro file. In this process, I used Gromos FF. 

I got the error in the actual run and the message is as follows:

===============================================================
protein  1:    1( 1) --  226(25):
        ALA ASN PHE LEU VAL HIS SER SER ASN ASN PHE GLY ALA ILE LEU SER SER THR ASN VAL GLY SER ASN THR TYR

Initializing protein models...!WARNING!: atom HD1 at protein #1 AA #6. if it is a terminal N, then no H attached! if it is not, then there could be a H missing!
!!ERROR!!: protein #1 AA #25 cannot find atom O in itself or the next AA! check the model library or the coordinate file! Initialization.c:1117

===============================================================

I attached my .gro file here. Could you please go over my file and briefly explain the reason and solution of the error? And even though I followed the way to create .gro file explained in the manual, it seems that it is not working properly. Could you provide an alternative way to create .gro file for running without errors? Thank you.

Kye

[test .gro.txt](https://github.com/alexzheng42/sDMD/files/8185220/test.gro.txt)

**Comment by alexzheng42** [comment]
Thank you very much for reporting the bug! It has been fixed. I tested your .gro file and it should work now. Please feel free to let me know if you would have any other questions.
